{% set name = 'rdt' %}
{% set version = '0.5.2' %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install ."

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6,<3.9
    - numpy >=1.18.0,<2
    - pandas >=1.1,<1.1.5
    - scipy >=1.4.1,<2
  run:
    - python >=3.6,<3.9
    - numpy >=1.18.0,<2
    - pandas >=1.1,<1.1.5
    - scipy >=1.4.1,<2

about:
  home: "https://github.com/sdv-dev/RDT"
  license: MIT
  license_family: MIT
  license_file:
  summary: "Reversible Data Transforms"
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - sdv-dev
