{% set name = 'rdt' %}
{% set version = '0.6.3.dev3' %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install ."

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6,<3.10
    - numpy >=1.18.0,<2
    - pandas >=1.1.3,<2
    - scipy >=1.5.4,<2
    - psutil >=5.7,<6
    - scikit-learn >=0.24,<2
    - pyyaml >=5.4.1,<6
  run:
    - python >=3.6,<3.10
    - numpy >=1.18.0,<2
    - pandas >=1.1.3,<2
    - scipy >=1.5.4,<2
    - psutil >=5.7,<6
    - scikit-learn >=0.24,<2
    - pyyaml >=5.4.1,<6

about:
  home: "https://github.com/sdv-dev/RDT"
  license: MIT
  license_family: MIT
  license_file:
  summary: "Reversible Data Transforms"
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - sdv-dev
