name: Performance Tests

on:
  - push
  - pull_request

jobs:
  performance:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install invoke
        pip install .[test]
    - name: Test performance
      run: invoke performance
