name: Release
on:
  release:
    types: [published]

jobs:
  release:
    uses: ./.github/workflows/publish.yml   
    with: 
      candidate: false
      test_pypi: false
  release-download-tracker:
    uses: ./.github/workflows/publish_download_tracker.yml
    with:
      source_branch: 'stable'
